### ISSUE TITLE
"Invalid cast"?

### ISSUE THREAD

**Issue by endel** [deniszykov/msgpack-unity3d#8]
Hey there,

I'm curious why I can't cast a value directly to `int`? See my REPL output:

```
> message[4]
53
> (int) message[4]
Invalid cast.
> (uint) message[4]
Invalid cast.
> (byte) message[4]
53
```

Isn't `53` castable to `int`?

Cheers!

**Comment by endel** [comment]
This is really annoying :( when the number grows, it cannot be casted to `byte` anymore, and neither `int`, but it works for `uint`.

```
> message[4]
85113
> (int)message[4]
Invalid cast.
> (byte)message[4]
Invalid cast.
> (uint)message[4]
85113
```

**Comment by deniszykov** [comment]
Hi @endel. You are trying to [unbox](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/boxing-and-unboxing) wrong type. Unbox operation is not 'conversion' to desired type it is 'extraction' value of desired type from object. 

MessagePack serializer doesn't preserve number type during serialization/deserialization process. It is inherited from [message pack format](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/boxing-and-unboxing). For example when you serialize 1024(Int32) it would be written as 0xcd[uint 16] token and deserialized as UInt16. 

Easiest approach to workaround this problem is to use [Convert.ToInt32](https://msdn.microsoft.com/en-us/library/system.convert.toint32(v=vs.110).aspx) method.

**Comment by endel** [comment]
Awesome, thanks for the clarification!
